# Render deployment configuration for AI Agent Financial Advisor
services:
  # Web service for the Phoenix application
  - type: web
    name: ai-agent-financial-advisor
    env: elixir
    plan: starter
    buildCommand: ./render-build.sh
    startCommand: _build/prod/rel/ai_agent/bin/server
    healthCheckPath: /health
    envVars:
      - key: MIX_ENV
        value: prod
      - key: PORT
        value: 8080
      - key: PHX_HOST
        fromService:
          name: ai-agent-financial-advisor
          type: web
          property: host
      - key: PHX_SERVER
        value: true
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ai-agent-database
          property: connectionString
      - key: POOL_SIZE
        value: 10
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: HUBSPOT_CLIENT_ID
        sync: false
      - key: HUBSPOT_CLIENT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false

# PostgreSQL database with pgvector extension
databases:
  - name: ai-agent-database
    plan: starter
    databaseName: ai_agent_prod
    user: ai_agent
    postgresMajorVersion: 15
    ipAllowList: []
    extensions:
      - vector
